server:
  http: "\${SERVER_PORT:8080}"

spring:
  application:
    name: ${artifactId}
    version: ${version}
  jmx.enabled: true
  threads:
    virtual:
      enabled: true
management:
  info:
    build.enabled: true
    java.enabled: true
    git.enabled: true
  otlp.metrics.export.enabled: "\${TRACING_EXPORT:false}"
  tracing:
    sampling.probability: "\${TRACING_SAMPLING_PROBABILITY:1.0}"
  observations:
    http.server:
      filter.order: -100
  endpoints:
    jmx:
      exposure.include: "*"
    web:
      exposure:
        include: health, info, prometheus, metrics
      base-path: /actuator
  endpoint:
    health:
      probes.enabled: true
      logging.slow-indicator-threshold: "\${HEALTH_ACTUATOR_LOGGER_TIMEOUT_DURATION:PT1S}"
      show-details: "\${HEALTH_ACTUATOR_SHOW_DETAILS:when-authorized}"
      group:
        readiness.include: "*"
        liveness.include: livenessState,diskSpace,ping
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${artifactId}
    export:
      prometheus:
        enabled: true
        step: 1m
        descriptions: true
    enable:
      jvm: true
      process: true
      system: true
      http: true
      logback: true

logging:
  level:
    root: "\${LOG_LEVEL_ROOT:INFO}"
    it.gov.pagopa: "\${LOG_LEVEL_PAGOPA:INFO}"
    org.springframework: "\${LOG_LEVEL_SPRING:INFO}"
    org.springframework.boot.availability: "\${LOG_LEVEL_SPRING_BOOT_AVAILABILITY:DEBUG}"
    it.gov.pagopa.mypay2pu.extractor.exception.ControllerExceptionHandler: "\${LOGGING_LEVEL_API_REQUEST_EXCEPTION:INFO}"
    org.springdoc.core.utils.SpringDocAnnotationsUtils: "\${LOG_LEVEL_SPRING_DOC:ERROR}"
    PERFORMANCE_LOG: "\${LOG_LEVEL_PERFORMANCE_LOG:INFO}"
    PERFORMANCE_LOG.API_REQUEST: "\${LOG_LEVEL_PERFORMANCE_LOG_API_REQUEST:\${logging.level.PERFORMANCE_LOG}}"
    PERFORMANCE_LOG.REST_INVOKE: "\${LOG_LEVEL_PERFORMANCE_LOG_REST_INVOKE:\${logging.level.PERFORMANCE_LOG}}"

rest:
  defaults:
    connection-pool:
      size: "\${DEFAULT_REST_CONNECTION_POOL_SIZE:10}"
      size-per-route: "\${DEFAULT_REST_CONNECTION_POOL_SIZE_PER_ROUTE:5}"
      time-to-live-minutes: "\${DEFAULT_REST_CONNECTION_POOL_TIME_TO_LIVE_MINUTES:10}"
    timeout:
      connect-millis: "\${DEFAULT_REST_TIMEOUT_CONNECT_MILLIS:120000}"
      read-millis: "\${DEFAULT_REST_TIMEOUT_READ_MILLIS:120000}"
  mydictionary:
    base-url: "\${MYDICTIONARY_BASE_URL:}"

datasource:
  mp4:
    jdbc-url: "jdbc:postgresql://\${MP4_DB_HOST}:\${MP4_DB_PORT:5432}/\${MP4_DB_NAME}"
    username: "\${MP4_DB_USER}"
    password: "\${MP4_DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  fesp:
    jdbc-url: "jdbc:postgresql://\${FESP_DB_HOST}:\${FESP_DB_PORT:5432}/\${FESP_DB_NAME}"
    username: "\${FESP_DB_USER}"
    password: "\${FESP_DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  mpv4:
    jdbc-url: "jdbc:postgresql://\${MPV4_DB_HOST:}:\${MPV4_DB_PORT:5432}/\${MPV4_DB_NAME:}"
    username: "\${MPV4_DB_USER:}"
    password: "\${MPV4_DB_PASSWORD:}"
    driver-class-name: org.postgresql.Driver

mypivot:
  enabled: "\${MYPIVOT_ENABLED:false}"

extractor:
  async:
    core-pool-size: "\${ASYNC_CORE_POOL_SIZE:2}"
    max-pool-size: "\${ASYNC_MAX_POOL_SIZE:5}"
    queue-capacity: "\${ASYNC_QUEUE_CAPACITY:10}"
  export:
    storage-path: "\${STORAGE_PATH:\${extractor.export.temp-base-dir}}"
    temp-base-dir: "\${TMP_FOLDER:\${java.io.tmpdir}}"
    broker-cf: "\${BROKER_CF:\${PA_IDENTIFICATIVO_INTERMEDIARIO_PA:00123456789}}"
    broker-ipa-code: "\${BROKER_IPA_CODE:\${PA_COD_IPA_ENTE_PREDEFINITO:IPA_DEFAULT}}"
    file-type-configurations:
      ORGANIZATIONS:
        export-page-size: "\${EXPORT_PAGE_SIZE_ORGANIZATIONS:1000}"
      ORG_SIL_SERVICES:
        export-page-size: "\${EXPORT_PAGE_SIZE_ORG_SIL_SERVICES:1000}"
      DEBT_POSITIONS_TYPE:
        export-page-size: "\${EXPORT_PAGE_SIZE_DEBT_POSITIONS_TYPE:1000}"
      DEBT_POSITIONS_TYPE_ORG:
        export-page-size: "\${EXPORT_PAGE_SIZE_DEBT_POSITIONS_TYPE_ORG:1000}"
      DEBT_POSITIONS_TYPE_ORG_OPERATORS:
        export-page-size: "\${EXPORT_PAGE_SIZE_DEBT_POSITIONS_TYPE_ORG_OPERATORS:1000}"
      DEBT_POSITIONS:
        export-page-size: "\${EXPORT_PAGE_SIZE_DEBT_POSITIONS:1000}"
      DEBT_POSITIONS_PAID:
        export-page-size: "\${EXPORT_PAGE_SIZE_DEBT_POSITIONS_PAID:1000}"
      PAYMENT_NOTIFICATION:
        export-page-size: "\${EXPORT_PAGE_SIZE_PAYMENT_NOTIFICATION:1000}"
  basic-auth:
    username: "\${CLIENT_ID:client}"
    password: "\${CLIENT_SECRET:secret}"

mypay:
  global-properties:
    notificaIo.markdown: "\${MYPAY_PROP_NOTIFICA_IO_MARKDOWN:}"
    notificaIo.subject: "\${MYPAY_PROP_NOTIFICA_IO_SUBJECT:}"

cipher:
  file-encrypt-enabled: "\${FILE_ENCRYPT_ENABLED:false}"
  file-encrypt-psw: "\${FILE_ENCRYPT_PSW:default_password}"

csv:
  separator: "\${CSV_SEPARATOR_CHAR:;}"
  quote-char: "\${CSV_QUOTE_CHAR:\\\"}"
